// This file was auto-generated by prisma-generator-typescript-interfaces

export type SubscriptionsType_enum = "news" | "blog";

export interface main_config_model_type {
  id: string;
  config_key: string;
  config_value: string;
  created_at: Date;
  update_at: Date;
}

export interface users_model_type {
  id: string;
  first_name: string;
  last_name: string | null;
  address: string | null;
  address2: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  phone: string | null;
  email: string | null;
  picture: string | null;
  roles: string[];
  posts?: posts_model_type | null;
  oauth_sessions?: oauth_sessions_model_type | null;
  created_at: Date;
  update_at: Date;
  orders?: orders_model_type[];
  subscriptions?: subscriptions_model_type[];
}

export interface oauth_sessions_model_type {
  id: string;
  user_id: string;
  users?: users_model_type;
  session_id: string | null;
  provider_type: string | null;
  access_token: string | null;
  access_expires_at: Date | null;
  refresh_token: string | null;
  created_at: Date;
}

export interface posts_model_type {
  id: string;
  user_id: string;
  users?: users_model_type;
  title: string | null;
  content: string | null;
  images: string[];
  published: boolean;
  created_at: Date;
  updated_at: Date;
}

export interface product_categories_model_type {
  id: string;
  title: string;
  position: number;
  image_url: string;
  created_at: Date;
  updated_at: Date;
  products?: products_model_type[];
}

export interface products_model_type {
  id: string;
  slug: string;
  position: number;
  images: string[];
  social_media_links: JsonValue | null;
  title: string;
  short_description: string;
  description: string | null;
  category_id: string | null;
  product_categories?: product_categories_model_type | null;
  quantity: number;
  item_weight_primary: number;
  item_weight_secondary: number;
  item_length: number;
  item_width: number;
  item_height: number;
  price: Decimal;
  is_new: boolean;
  is_available: boolean;
  is_frozen: boolean;
  is_coming_soon: boolean;
  is_deleted: boolean;
  created_at: Date;
  updated_at: Date;
}

export interface feedback_requests_model_type {
  id: string;
  title: string | null;
  content: string | null;
  hide_content: string | null;
  user_full_name: string | null;
  user_email: string | null;
  user_address: string | null;
  user_phone: string | null;
  from_path: string | null;
  created_at: Date;
  update_at: Date;
  processed: boolean;
}

export interface images_model_type {
  id: string;
  image_url: string;
  image_type: string;
  image_size: number;
  created_at: Date;
  update_at: Date;
}

export interface orders_model_type {
  id: string;
  user_id: string;
  users?: users_model_type;
  payment_id: string;
  order_number: number;
  order_status: string;
  order_amount_subtotal: Decimal | null;
  order_amount_total: Decimal | null;
  order_amount_discount: Decimal | null;
  order_amount_shipping: Decimal | null;
  order_amount_tax: Decimal | null;
  order_items: JsonValue;
  payment_status: string;
  shipping_order_id: string | null;
  shipping_details: JsonValue;
  shipping_options: JsonValue;
  created_at: Date;
  update_at: Date;
}

export interface pre_orders_model_type {
  id: string;
  pre_order_number: number | null;
  product: JsonValue;
  product_quantity: number;
  user_address: string;
  user_full_name: string;
  user_email: string;
  content: string | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface subscriptions_model_type {
  id: string;
  user_id: string;
  users?: users_model_type;
  type: SubscriptionsType_enum;
  created_at: Date | null;
  updated_at: Date | null;
  is_active: boolean | null;
}

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;

type Decimal = { valueOf(): string };
